server:
    port: 9000
management:
    port: 9001
    address: 127.0.0.1
    

#crawler max duration in seconds
crawler_duration : 60

logging:
    level:
        root:ERROR
        org.springframework.web:ERROR
        fr.djoutsop:DEBUG

info:
    build:
        artifact:@project.artifactId@
        name:@project.name@
        description:@project.description@
        version:@project.version@


spring:
    thymeleaf:
        prefix:/thymeleaf/
        cache:false
    
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: true
    datasource:
        url: jdbc:h2:mem:manga_crawler;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        name:
        username: manga_crawler
        password:
    h2:
        console:
            enabled: true
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        database: H2
        show_sql: true
        hibernate:
            ddl-auto: none
            naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
            hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
    
liquibase:
    contexts: prod
    change-log: classpath:/liquibase/master.xml
